// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACHO2IdODhhY7SwOYBy6ZFladSVM-Doy8',
    appId: '1:398350844413:web:3ec15b6cc2f7eb26fe1994',
    messagingSenderId: '398350844413',
    projectId: 'fir-project-2763d',
    authDomain: 'fir-project-2763d.firebaseapp.com',
    storageBucket: 'fir-project-2763d.firebasestorage.app',
    measurementId: 'G-PLSC7Y9KND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz5o5WYKPwhwbqIqKkJzHrqKLpcG6Zh_c',
    appId: '1:398350844413:android:b32ab504e6bd54b8fe1994',
    messagingSenderId: '398350844413',
    projectId: 'fir-project-2763d',
    storageBucket: 'fir-project-2763d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjB_Vbb29dKryaT_L1feoI4qrGPtAKsNM',
    appId: '1:398350844413:ios:38e6ebf9fc91b021fe1994',
    messagingSenderId: '398350844413',
    projectId: 'fir-project-2763d',
    storageBucket: 'fir-project-2763d.firebasestorage.app',
    iosBundleId: 'com.example.property',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACHO2IdODhhY7SwOYBy6ZFladSVM-Doy8',
    appId: '1:398350844413:web:f6d4594a043e2713fe1994',
    messagingSenderId: '398350844413',
    projectId: 'fir-project-2763d',
    authDomain: 'fir-project-2763d.firebaseapp.com',
    storageBucket: 'fir-project-2763d.firebasestorage.app',
    measurementId: 'G-E2CQRYGTFK',
  );
}
